#!/usr/bin/env python

import argparse
from svm.spark import Spark as svm

parser = argparse.ArgumentParser()
parser.add_argument('-a','--activate'
                    )
parser.add_argument('-d','--deactivate',
                    action='store_true'
                    )
parser.add_argument('-l','--list',
                    action='store_true'
                    )
parser.add_argument('-i','--install',
                    )

options = parser.parse_args()

if options.activate:
    print("activating".format(options.activate))

if options.deactivate:
    svm.deactivate_spark()

if options.list:
    svm.print_version_list()

if options.install:
    svm.install(options.install)