#!/usr/bin/env python

import argparse
from svm.spark import Spark as svm

parser = argparse.ArgumentParser()
parser.add_argument('-a','--activate'
                    )
parser.add_argument('-d','--deactivate',
                    action='store_true'
                    )
parser.add_argument('-l','--list',
                    action='store_true'
                    )
parser.add_argument('-i','--install',
                    )

options = parser.parse_args()

if options.activate:
    svm.activate_spark(options.activate)

if options.deactivate:
    svm.deactivate_spark()

if options.list:
    svm.print_version_list()

if options.install:
    svm.install(options.install)

if not options.activate and not options.deactivate and not options.list and not options.install:
    svm.list_installed_versions()

print(options)